// <auto-generated />
using System;
using BlazingFlame.UniversalBanList.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlazingFlame.UniversalBanList.Migrations
{
    [DbContext(typeof(BanListContext))]
    [Migration("20230605025015_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BlazingFlame.UniversalBanList.Models.UniversalBanWhitelist", b =>
                {
                    b.Property<uint>("BanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("BanId");

                    b.ToTable("uBanList_universal_ban_whitelists");
                });
#pragma warning restore 612, 618
        }
    }
}
